### ISSUE TITLE
Backend Javascript

### ISSUE THREAD

**Issue by nathankwon98** [jrivera115/team-repo-inst377#17]
Work on cleaning and simplifying data set

**Comment by jrivera115** [comment]
I can't turn the data into a JSON object. It keeps outputting on the HTML inside a pre tag. Not sure if I am doing this correctly.

```

app.get('/', (req, res) => {
  const baseURL = 'https://data.princegeorgescountymd.gov/resource/umjn-t2iz.json';
  fetch(baseURL)
    .then((r) => r.json())
    .then((r) => r.map((dataset) => dataset.name))
    .then((data) => {
      console.log(data);
      return data;
    })
    .catch((err) => {
      console.log(err);
      res.redirect('/error');
    });
});
```

**Comment by jrivera115** [comment]
I closed it without thinking. My bad.

**Comment by jrivera115** [comment]
Update: if I run the code above ^ it just keeps loading. After it loads it just says: localhost didn't send any data ERR_EMPTY_RESPONSE. But I get output from my Git Bash.

**Comment by jrivera115** [comment]
Fixed the errors above.
